[book]
title       = "localcache — Documentation"
authors     = ["nabbisen"]
language    = "en"
src         = "src"

[output.html]
git-repository-url = "https://github.com/nabbisen/localcache"
edit-url-template  = "https://github.com/nabbisen/localcache/edit/main/docs/{path}"
